import torch

def interpolate(history, scale_factor):
    T, V = history.shape
    history = history.permute(1, 0).view(1, V, T)
    history = torch.nn.functional.interpolate(history, scale_factor=scale_factor, mode='linear', align_corners=False)
    history = history.squeeze().permute(1, 0)
    return history

def mix(audio):
    mix = torch.sum(audio, dim=1)
    mix /= torch.max(torch.abs(mix))
    return (mix * 32767).to(torch.int16)

def get_stereo_masks(timesteps: int, channels: int):
    left_mask = torch.arange(1, 0, -1/channels).unsqueeze(0).repeat(timesteps, 1)
    right_mask = torch.ones(channels).unsqueeze(0).repeat(timesteps, 1) - left_mask
    return left_mask, right_mask

def get_diff_mask(history: torch.Tensor, note_length, fs=44100):
    T, C = history.shape
    samples_per_note = int(fs * note_length)
    diff = torch.diff(history, dim=0)
    diff = torch.cat((
        torch.zeros(1, C), 
        diff, 
        torch.zeros(1, C)
    ), dim=0)
    diff = torch.abs(diff)
    diff = diff / torch.max(diff)
    diff = interpolate(diff, samples_per_note)
    diff = diff[samples_per_note // 2 : -samples_per_note // 2]
    return diff

def sonify(history: torch.Tensor, note_length, fs=44100, do_stereo=True, do_interpolate=False, do_diff=False):
    """
    Partially generated by GPT-4o, GPT-5 mini (OpenAI, Jan 2026)
    """
    # history = history.cpu().numpy() # (T, V)
    T, V = history.shape
    samples_per_note = int(fs * note_length)

    if do_interpolate:
        freq_samples = interpolate(history, samples_per_note)
    else:
        freq_samples = torch.repeat_interleave(history, samples_per_note, dim=0)
    # freq_samples = freq_samples.to(torch.float64)

    delta = 2 * torch.pi * freq_samples / float(fs) # phase increment per sample
    phase = torch.cumsum(delta, axis=0) # integrate
    phase = torch.fmod(phase, 2 * torch.pi) # wrap phase

    audio = torch.sin(phase)
    if do_diff:
        diff_mask = get_diff_mask(history, note_length)
        audio *= diff_mask

    if do_stereo:
        T, C = audio.shape

        left_mask, right_mask = get_stereo_masks(T, C)
        stereo = torch.stack((
            mix(audio * left_mask), 
            mix(audio * right_mask)
        ))
        stereo = stereo.permute(1, 0)

        return stereo
    else:
        wav = mix(audio)
        return wav

def normalize(x, lower=50, upper=2050):
    z = (x - x.mean()) / x.std()
    return (z + 2) * (upper-lower) / 4 + lower
