import torch
import plot
from timer import Timer
from data import normalize

def interpolate(history, scale_factor):
    """ Interpolate a (time, voices)-tensor to shape (time * scale_factor, voices) """
    T, V = history.shape
    history = history.permute(1, 0).view(1, V, T) # (1, V, T)

    history = torch.nn.functional.interpolate(
        history, 
        scale_factor=scale_factor, 
        mode='linear', 
        align_corners=False
    ) # (1, V, T * scale)

    history = history.squeeze().permute(1, 0) # (T * scale, V)
    return history

def generate_phase(frequencies, fs=44100):
    """
    Given a (timesteps, voices)-tensor, output a (time, voices)-tensor of phases
    where time = timesteps * fs
    """
    delta = 2 * torch.pi * frequencies / float(fs) # phase increment per sample
    phase = torch.cumsum(delta, axis=0) # integrate
    phase = torch.fmod(phase, 2 * torch.pi) # wrap phase to prevent overflow
    return phase

def mix(audio):
    """ Sum the voice channels of a (time, voices)-tensor, normalize to int16 """
    mix = torch.sum(audio, dim=1)
    mix /= torch.max(torch.abs(mix))
    return (mix * 32767).to(torch.int16)

def get_stereo_masks(timesteps: int, voices: int):
    """
    Generate L and R stereo masks of size (1, voices), with 
    linear variation across the voices dimension. To be multiplied
    with audio tensor. 
    """
    left_mask = torch.arange(1, 0, -1/voices).unsqueeze(0)
    right_mask = torch.ones(voices).unsqueeze(0) - left_mask
    return left_mask, right_mask

def mix_stereo(audio): 
    T, C = audio.shape

    left_mask, right_mask = get_stereo_masks(T, C)
    #timer.log("stereo masks generated")
    left = audio * left_mask
    right = audio * right_mask
    #timer.log("stereo channels masked")
    stereo = (
        mix(left), 
        mix(right)
    )
    #timer.log("stereo mixed")
    stereo = torch.stack(stereo)
    stereo = stereo.permute(1, 0)
    return stereo

def get_diff_mask(history: torch.Tensor, note_length, fs=44100):
    """
    Generate a (time, voices) mask to weigh an audio tensor's amplitude
    depending on the interpolated derivative of time
    """
    T, C = history.shape
    samples_per_note = int(fs * note_length)

    diff = torch.abs(torch.diff(history, dim=0))

    diff = torch.cat((
        torch.zeros(1, C), 
        diff, 
        torch.zeros(1, C)
    ), dim=0) # padded first derivative

    diff = interpolate(diff, samples_per_note)
    diff = diff[samples_per_note // 2 : -samples_per_note // 2] # crop to fit
    diff = normalize(diff, 0, 1)
    return diff

def sonify(history: torch.Tensor, note_length, fs=44100, do_stereo=True, do_interpolate=False, do_diff=False):
    """
    Sonify a tensor of shape (timesteps, voices)
    Partially generated by GPT-4o, GPT-5 mini (OpenAI, Jan 2026)
    """
    timer = Timer()

    T, V = history.shape
    samples_per_note = int(fs * note_length)

    if do_interpolate:
        freq_samples = interpolate(history, samples_per_note)
    else:
        freq_samples = torch.repeat_interleave(history, samples_per_note, dim=0)

    timer.log("repeating completed")

    phase = generate_phase(freq_samples)
    timer.log("phase generated")
    audio = torch.sin(phase)
    timer.log("waveform generated")

    if do_diff:
        diff_mask = get_diff_mask(history, note_length)
        audio *= diff_mask

    if do_stereo:
        stereo = mix_stereo(audio)
        return stereo
    else:
        wav = mix(audio)
        timer.log("mono mixing complete")
        return wav

def gainson(gains: torch.Tensor, freq_map: torch.Tensor, note_length, fs=44100, do_stereo=True):
    timer = Timer()

    T, V = gains.shape
    gains = normalize(gains, lower=0, upper=0.9)
    samples_per_note = int(fs * note_length)

    if len(freq_map.shape) == 1:

        if freq_map.shape[0] != gains.shape[1]:
            raise ValueError("1D freq_map must match voice dimension of gains")
        freq_map = freq_map.unsqueeze(0)
        # freq_map = freq_map.repeat(T, 1)
        timer.log("shape adjusted to 2D")

    elif list(freq_map.shape) != list(gains.shape): 
        raise ValueError("2D freq_map must match shape of gains")
    
    freq_samples = torch.repeat_interleave(freq_map, samples_per_note, dim=0)
    gain_samples = torch.repeat_interleave(gains, samples_per_note, dim=0)
    timer.log("repeat_interleave complete")

    phase = generate_phase(freq_samples)
    timer.log("phase generated")
    audio = torch.sin(phase)
    timer.log("waveform generated")
    audio *= gain_samples

    if do_stereo:
        stereo = mix_stereo(audio)
        timer.log("stereo mixed")
        return stereo
    else:
        wav = mix(audio)
        return wav